# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250128-172455-abstract-turkey

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: tr

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 1
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: true
    hidden_layers_sizes: {"text": [64, 32]}
    embedding_dimension: 16
    number_of_transformer_layers: 1
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 20
    constrain_similarities: true
    hidden_layers_sizes: [32, 16]
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 2
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 2
    epochs: 20
    batch_size: 16
    hidden_layers_sizes: [16, 8]
    embedding_dimension: 16
    constrain_similarities: true
